version: '3.5'

services:

  nodejs:
    build:
      context: .
      args:
        - NODE_ENV=development
        - NOMEPROJETO=PlantManager
    container_name: nodejs
    environment:
      - NODE_ENV=development
      - NOMEPROJETO=PlantManager
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
      - '19000:19000'
      - '3333:3333'
    volumes:
      - './Projetos:/opt'
    healthcheck:
      disable: true