version: '3.5'

volumes:
  nodejs-data:
    driver: local

services:

  nodejs:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: nodejs
    environment:
      - NODE_ENV=development
      - NOMEPROJETO=PlantManager
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./Projetos:/opt
      - nodejs-data:/opt/PlantManager
    healthcheck:
      disable: true